#ifndef BUILDINFO_H
#define BUILDINFO_H

#include <string>

/// @file buildinfo.h
/// @brief Build information for the maze builder library
/// @details This file contains the version, commit SHA, and timestamp of the build
/// @details The commit SHA is the SHA of the last commit when "buildinfo.h" was generated by the build system

namespace mazes {

/// @class build_info
/// @brief Build information for the maze builder library
struct build_info {
    static inline const std::string CommitSHA = "'7e10522'";
    static inline const std::string Timestamp = "2025-02-21T08:01:19";
    static inline const std::string Version = "6.0.1";
};

}

#endif // buildinfo.h

